//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresPio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ButtonFace")]
        public global::System.Drawing.Color PColor1 {
            get {
                return ((global::System.Drawing.Color)(this["PColor1"]));
            }
            set {
                this["PColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PicPath {
            get {
                return ((string)(this["PicPath"]));
            }
            set {
                this["PicPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImgPath {
            get {
                return ((string)(this["ImgPath"]));
            }
            set {
                this["ImgPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Publish_Chek1 {
            get {
                return ((bool)(this["Publish_Chek1"]));
            }
            set {
                this["Publish_Chek1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Publish_Chek2 {
            get {
                return ((bool)(this["Publish_Chek2"]));
            }
            set {
                this["Publish_Chek2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Publish_Chek3 {
            get {
                return ((bool)(this["Publish_Chek3"]));
            }
            set {
                this["Publish_Chek3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Publish_Chek4 {
            get {
                return ((bool)(this["Publish_Chek4"]));
            }
            set {
                this["Publish_Chek4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Publish_Chek5 {
            get {
                return ((bool)(this["Publish_Chek5"]));
            }
            set {
                this["Publish_Chek5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Publish_Chek6 {
            get {
                return ((bool)(this["Publish_Chek6"]));
            }
            set {
                this["Publish_Chek6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Publish_Chek7 {
            get {
                return ((bool)(this["Publish_Chek7"]));
            }
            set {
                this["Publish_Chek7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Publish_Chek8 {
            get {
                return ((bool)(this["Publish_Chek8"]));
            }
            set {
                this["Publish_Chek8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Publish_URL {
            get {
                return ((string)(this["Publish_URL"]));
            }
            set {
                this["Publish_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Replace {
            get {
                return ((bool)(this["Replace"]));
            }
            set {
                this["Replace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int GradeColorN {
            get {
                return ((int)(this["GradeColorN"]));
            }
            set {
                this["GradeColorN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Pla_N1 {
            get {
                return ((bool)(this["Pla_N1"]));
            }
            set {
                this["Pla_N1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Pla_N2 {
            get {
                return ((bool)(this["Pla_N2"]));
            }
            set {
                this["Pla_N2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Pla_N3 {
            get {
                return ((bool)(this["Pla_N3"]));
            }
            set {
                this["Pla_N3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Pla_N4 {
            get {
                return ((bool)(this["Pla_N4"]));
            }
            set {
                this["Pla_N4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float Pla_size {
            get {
                return ((float)(this["Pla_size"]));
            }
            set {
                this["Pla_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Uni_C1 {
            get {
                return ((bool)(this["Uni_C1"]));
            }
            set {
                this["Uni_C1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Uni_C2 {
            get {
                return ((bool)(this["Uni_C2"]));
            }
            set {
                this["Uni_C2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Uni_C3 {
            get {
                return ((bool)(this["Uni_C3"]));
            }
            set {
                this["Uni_C3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Uni_C4 {
            get {
                return ((bool)(this["Uni_C4"]));
            }
            set {
                this["Uni_C4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Uni_C5 {
            get {
                return ((bool)(this["Uni_C5"]));
            }
            set {
                this["Uni_C5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Uni_C6 {
            get {
                return ((bool)(this["Uni_C6"]));
            }
            set {
                this["Uni_C6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Uni_C7 {
            get {
                return ((bool)(this["Uni_C7"]));
            }
            set {
                this["Uni_C7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Uni_C8 {
            get {
                return ((bool)(this["Uni_C8"]));
            }
            set {
                this["Uni_C8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("图表")]
        public string Uni_T1 {
            get {
                return ((string)(this["Uni_T1"]));
            }
            set {
                this["Uni_T1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("图片")]
        public string Uni_T2 {
            get {
                return ((string)(this["Uni_T2"]));
            }
            set {
                this["Uni_T2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("媒体")]
        public string Uni_T3 {
            get {
                return ((string)(this["Uni_T3"]));
            }
            set {
                this["Uni_T3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("表格")]
        public string Uni_T4 {
            get {
                return ((string)(this["Uni_T4"]));
            }
            set {
                this["Uni_T4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("文本")]
        public string Uni_T5 {
            get {
                return ((string)(this["Uni_T5"]));
            }
            set {
                this["Uni_T5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("线条")]
        public string Uni_T6 {
            get {
                return ((string)(this["Uni_T6"]));
            }
            set {
                this["Uni_T6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("形状")]
        public string Uni_T7 {
            get {
                return ((string)(this["Uni_T7"]));
            }
            set {
                this["Uni_T7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("组合")]
        public string Uni_T8 {
            get {
                return ((string)(this["Uni_T8"]));
            }
            set {
                this["Uni_T8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Podpath {
            get {
                return ((string)(this["Podpath"]));
            }
            set {
                this["Podpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PodNstr {
            get {
                return ((string)(this["PodNstr"]));
            }
            set {
                this["PodNstr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PodOstr {
            get {
                return ((string)(this["PodOstr"]));
            }
            set {
                this["PodOstr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Temp_Path {
            get {
                return ((string)(this["Temp_Path"]));
            }
            set {
                this["Temp_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("msoShapeRectangle")]
        public global::Microsoft.Office.Core.MsoAutoShapeType Shape_Style {
            get {
                return ((global::Microsoft.Office.Core.MsoAutoShapeType)(this["Shape_Style"]));
            }
            set {
                this["Shape_Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public float Shape_Tra {
            get {
                return ((float)(this["Shape_Tra"]));
            }
            set {
                this["Shape_Tra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Shape_Color {
            get {
                return ((global::System.Drawing.Color)(this["Shape_Color"]));
            }
            set {
                this["Shape_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("样稿水印")]
        public string WaterText {
            get {
                return ((string)(this["WaterText"]));
            }
            set {
                this["WaterText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public float WaterSize {
            get {
                return ((float)(this["WaterSize"]));
            }
            set {
                this["WaterSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int WaterColumn {
            get {
                return ((int)(this["WaterColumn"]));
            }
            set {
                this["WaterColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int WaterRow {
            get {
                return ((int)(this["WaterRow"]));
            }
            set {
                this["WaterRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("微软雅黑")]
        public string WaterFont {
            get {
                return ((string)(this["WaterFont"]));
            }
            set {
                this["WaterFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color WaterColor {
            get {
                return ((global::System.Drawing.Color)(this["WaterColor"]));
            }
            set {
                this["WaterColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Group2 {
            get {
                return ((bool)(this["Group2"]));
            }
            set {
                this["Group2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Group3 {
            get {
                return ((bool)(this["Group3"]));
            }
            set {
                this["Group3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Group4 {
            get {
                return ((bool)(this["Group4"]));
            }
            set {
                this["Group4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Group5 {
            get {
                return ((bool)(this["Group5"]));
            }
            set {
                this["Group5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Group6 {
            get {
                return ((bool)(this["Group6"]));
            }
            set {
                this["Group6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Group7 {
            get {
                return ((bool)(this["Group7"]));
            }
            set {
                this["Group7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int GlowNum {
            get {
                return ((int)(this["GlowNum"]));
            }
            set {
                this["GlowNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double GlowTra {
            get {
                return ((double)(this["GlowTra"]));
            }
            set {
                this["GlowTra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color GlowColor {
            get {
                return ((global::System.Drawing.Color)(this["GlowColor"]));
            }
            set {
                this["GlowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color ShodwColor {
            get {
                return ((global::System.Drawing.Color)(this["ShodwColor"]));
            }
            set {
                this["ShodwColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85")]
        public double ShodwTra {
            get {
                return ((double)(this["ShodwTra"]));
            }
            set {
                this["ShodwTra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102")]
        public float ShodwSize {
            get {
                return ((float)(this["ShodwSize"]));
            }
            set {
                this["ShodwSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float ShodwBlur {
            get {
                return ((float)(this["ShodwBlur"]));
            }
            set {
                this["ShodwBlur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float ShodwX {
            get {
                return ((float)(this["ShodwX"]));
            }
            set {
                this["ShodwX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float ShodwY {
            get {
                return ((float)(this["ShodwY"]));
            }
            set {
                this["ShodwY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("msoFalse")]
        public global::Microsoft.Office.Core.MsoTriState ShodwCheck {
            get {
                return ((global::Microsoft.Office.Core.MsoTriState)(this["ShodwCheck"]));
            }
            set {
                this["ShodwCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Grastep {
            get {
                return ((int)(this["Grastep"]));
            }
            set {
                this["Grastep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public float Gragra {
            get {
                return ((float)(this["Gragra"]));
            }
            set {
                this["Gragra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Gracolor {
            get {
                return ((int)(this["Gracolor"]));
            }
            set {
                this["Gracolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MockFile {
            get {
                return ((string)(this["MockFile"]));
            }
            set {
                this["MockFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double Pa_Spaced {
            get {
                return ((double)(this["Pa_Spaced"]));
            }
            set {
                this["Pa_Spaced"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextBoxAuto {
            get {
                return ((bool)(this["TextBoxAuto"]));
            }
            set {
                this["TextBoxAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Regular")]
        public global::System.Drawing.FontStyle WaterFonts {
            get {
                return ((global::System.Drawing.FontStyle)(this["WaterFonts"]));
            }
            set {
                this["WaterFonts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("196, 62, 28")]
        public global::System.Drawing.Color iconColor {
            get {
                return ((global::System.Drawing.Color)(this["iconColor"]));
            }
            set {
                this["iconColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MockupUrl {
            get {
                return ((string)(this["MockupUrl"]));
            }
            set {
                this["MockupUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string exportFolderPath {
            get {
                return ((string)(this["exportFolderPath"]));
            }
            set {
                this["exportFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public float WaterRotation {
            get {
                return ((float)(this["WaterRotation"]));
            }
            set {
                this["WaterRotation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public float WaterOpacity {
            get {
                return ((float)(this["WaterOpacity"]));
            }
            set {
                this["WaterOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ApplyToMaster {
            get {
                return ((bool)(this["ApplyToMaster"]));
            }
            set {
                this["ApplyToMaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSize {
            get {
                return ((bool)(this["AutoSize"]));
            }
            set {
                this["AutoSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowEdit {
            get {
                return ((bool)(this["AllowEdit"]));
            }
            set {
                this["AllowEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int JPEGQuality {
            get {
                return ((int)(this["JPEGQuality"]));
            }
            set {
                this["JPEGQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{filename}_Page{number}")]
        public string NamePattern {
            get {
                return ((string)(this["NamePattern"]));
            }
            set {
                this["NamePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenAfterExport {
            get {
                return ((bool)(this["OpenAfterExport"]));
            }
            set {
                this["OpenAfterExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreateSubFolder {
            get {
                return ((bool)(this["CreateSubFolder"]));
            }
            set {
                this["CreateSubFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentColors"]));
            }
            set {
                this["RecentColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int PPtDPI {
            get {
                return ((int)(this["PPtDPI"]));
            }
            set {
                this["PPtDPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImageGalleryUrl")]
        public string ImageGalleryUrl {
            get {
                return ((string)(this["ImageGalleryUrl"]));
            }
            set {
                this["ImageGalleryUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection ImageGalleryPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImageGalleryPaths"]));
            }
            set {
                this["ImageGalleryPaths"] = value;
            }
        }
    }
}
